django-web-dev-master/22_blog_api_drf/blog-api-starter/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.show_list, name='show_list'),
    path('<int:post_id>', views.show_post, name='show_post'),
]

django-web-dev-master/22_blog_api_drf/blog-api-starter/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

django-web-dev-master/22_blog_api_drf/blog-api-starter/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=140)
    text = models.TextField()
    published = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Post: {self.title[:15]}...'

django-web-dev-master/22_blog_api_drf/blog-api-starter/blog/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.
def show_list(request):
    posts = Post.objects.all().order_by('-id')
    return render(request, 'post_list.html', {'posts': posts})

def show_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    return render(request, 'post.html', {'post': post})

django-web-dev-master/22_blog_api_drf/blog-api-starter/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Blog</title>
</head>
<body>

<h1 class="text-center m-4">My Blog</h1>
<hr>

<div class="container">
{% block content %}

{% endblock content %}
</div>

</body>
</html>

django-web-dev-master/22_blog_api_drf/blog-api-starter/blog/templates/post.html
{% extends "base.html" %}

{% block content %}

<div>
<div class="row">
    <h1 class="col">{{ post.title }}</h1>
    <p class="col text-muted text-right">{{ post.published }}</p>
</div>
<div class="row">
    <p class="col">{{ post.text }}</p>
</div>
</div>

<footer><a href="{% url 'blog:show_list' %}">Back</a></footer>

{% endblock content %}

django-web-dev-master/22_blog_api_drf/blog-api-starter/blog/templates/post_list.html
{% extends "base.html" %}

{% block content %}
<div class="row">
{% for post in posts %}
<div class="card m-4" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{ post.title }}</h5>
    <p class="card-text text-muted small">{{ post.published }}</p>
    <p class="card-text">{{ post.text|truncatechars:30 }}</p>
    <a href="{% url 'blog:show_post' post.id %}" class="btn btn-primary">Read More</a>
  </div>
</div>
{% endfor %}
</div>

{% endblock content %}