django-web-dev-master/05_blog_overview/02_fix_sending_data_to_your_template/learning_log/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('learning_logs.urls')),
]

django-web-dev-master/05_blog_overview/02_fix_sending_data_to_your_template/learning_logs/urls.py
"""Defines URL patterns for learning_logs."""
from django.urls import path
from . import views


app_name = 'learning_logs'

urlpatterns = [
    # homepage
    path('', views.index, name='index'),
    # topics
    path('topics/', views.topics, name='topics'),
    # entries
    path('topics/<int:pk>/', views.entry, name='entry'),
]

django-web-dev-master/05_blog_overview/02_fix_sending_data_to_your_template/learning_logs/models.py
from django.db import models


class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Entry(models.Model):
    """Something specific learned about a Topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text

django-web-dev-master/05_blog_overview/02_fix_sending_data_to_your_template/learning_logs/views.py
from django.shortcuts import render
from .models import Topic, Entry


# Create your views here.
def index(request):
    """The home page for learning logs."""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """Displays a list of all available topics."""
    topics = Topic.objects.order_by('-date_added')
    return render(request, 'learning_logs/topics.html', {"topics": topics})

def entry(request, pk):
    """Displays the full text of a learning entry."""
    entry = Entry.objects.get(pk=pk)
    return render(request, 'learning_logs/entry.html', {'entry': entry})
    

django-web-dev-master/05_blog_overview/02_fix_sending_data_to_your_template/learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning Log</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<body>
    <nav>
        <a href="{% url 'learning_logs:index' %}">Learning Logs</a>
        <a href="{% url 'learning_logs:topics' %}">All Topics</a>
    </nav>
    {% block content %}
    
    {% endblock %}
</body>
</html>

django-web-dev-master/05_blog_overview/02_fix_sending_data_to_your_template/learning_logs/templates/learning_logs/entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
    
    <h1>Learning Entry</h1>

    <p>{{entry.text}}</p>
    <a href="{% url 'learning_logs:topics' %}">Back</a>

{% endblock %}

django-web-dev-master/05_blog_overview/02_fix_sending_data_to_your_template/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <h1>Learning Log</h1>
    <p>This app helps you keep track of what you're learning about.</p>

{% endblock %}

django-web-dev-master/05_blog_overview/02_fix_sending_data_to_your_template/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

<h1>Topics</h1>

{% for topic  in topics %}
{% for entry in topic.entry_set.all %}
<!-- 
    <h3>{{ topic.text }}</h3>
    <p>{{ entry.text|truncatechars:20 }}</p>
    <p>{{ topic.date_added }}</p>
    <hr> -->

</div>
<div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
  <div class="card-header">{{ topic.text }}</div>
  <div class="card-body">
    <h5 class="card-title">{{ topic.date_added }}</h5>
    <p class="card-text">{{ entry.text|truncatechars:20 }}</p>
  </div>
</div>
    

{% endfor %}
{% endfor %}


{% endblock %}